ukf_filter_node:
    # ros__parameters:
    #     frequency: 50.0
    #     two_d_mode: true
    #     publish_tf: true
 
    #     map_frame: map             
    #     odom_frame: odom            
    #     base_link_frame: base_footprint 
    #     world_frame: odom 

    #     #x     , y     , z,
    #     #roll  , pitch , yaw,
    #     #vx    , vy    , vz,
    #     #vroll , vpitch, vyaw,
    #     #ax    , ay    , az
    #     odom0: wheel/odometry
    #     odom0_config: [false, false, false,
    #                    false, false, false,
    #                    true, true, false,
    #                    false, false, true,
    #                    false, false, false]

    #     imu0: imu/data
    #     imu0_config: [false, false, false,
    #                   false, false, false,
    #                   false, false, false,
    #                   false, false, true,
    #                   false, false, false]
    ros__parameters:
        frequency: 50.0
        two_d_mode: true
        publish_tf: true

        map_frame: map             
        odom_frame: odom            
        base_link_frame: base_footprint 
        world_frame: odom 

        #x     , y     , z,
        #roll  , pitch , yaw,
        #vx    , vy    , vz,
        #vroll , vpitch, vyaw,
        #ax    , ay    , az
        odom0_type: wheel/odometry
        odom0_type: wheel/odometry
        odom0_initial_covariance: [0.0, 0.0, 0.0,
                                  0.0, 0.0, 0.0,
                                  1.0, 1.0, 0.0,
                                  0.0, 0.0, 0.0,
                                  0.0, 0.0, 0.0]

        imu0_type: imu/data
        imu0_initial_covariance: [0.0, 0.0, 0.0,
                                  0.0, 0.0, 0.0,
                                  1.0, 1.0, 0.0,
                                  0.0, 0.0, 1.0,
                                  0.0, 0.0, 0.0]